apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'springboot'
        metrics_path: '/probono/actuator/prometheus'
        static_configs:
          - targets: ['springboot-service:8999']