apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999
      nodePort: 30002 # NodePort는 30000-32767 범위에서 선택